# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "NC Piedmont DSA"
description: 

email: info@dsanc.org
#blog logo
logo: "/assets/images/DSA.png"
# blog cover
cover: "/assets/images/Revolution_wide.jpg"

name: "NC Piedmont DSA"
author: "NC Piedmont DSA"
author_image: "/assets/images/DSA-NCP.png"

paginate:	5

url: "https://www.dsanc.org" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
# twitter_handle: '@dirkfabisch'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/NC_DSA
    desc: Twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/TriangleTriadDSA
    desc: Facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/NCPiedmontDSA
    desc:	GitHub
    share_url:
    share_title:
    share_link:
        
  - icon:   rss
    url:    https://ncpiedmontdsa.github.io/feed.xml
    desc:   Feed

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
